# Generated by Django 3.1.3 on 2023-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auto_20231205_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='anonymous_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
